### ISSUE TITLE
Fork of jambonz freeswitch modules

### ISSUE THREAD

**Issue by rasheed-speechlogix** [mdslaney/drachtio-freeswitch-modules#1]
Hello , 

thank you for this fork . Did you take the fork of  / jambonz/freeswitch-modules which is the latest one . 

thanks 

Abdul Rasheed

**Comment by mdslaney** [comment]
No problem, this was a fork of **https://github.com/drachtio/drachtio-freeswitch-modules.git** about 2 weeks before it was removed.

Is this what you are looking for?
https://github.com/lylepratt/freeswitch-modules

**Comment by rasheed-speechlogix** [comment]
Hi , 
Thank you for your response... I was looking for https://github.com/jambonz/freeswitch-modules.git which was having the latest updates in it on this project.  https://github.com/drachtio/drachtio-freeswitch-modules.git   this was archived 1 year back i think . 

Thanks and Regards
Abdul Rasheed

**Comment by mdslaney** [comment]
Good luck :)

**Comment by rasheed-speechlogix** [comment]
Thank you Slaney.  i got more recent forks from https://github.com/lylepratt/freeswitch-modules  and it really worked well. Thank you for your support..  

Best Regards
Abdul Rasheed
